from typing import Dict, List, Any

DANGEROUS_COMMANDS: Dict[str, Dict[str, Any]] = {
    r"rm\s+-[a-zA-Z]*r[a-zA-Z]*f[a-zA-Z]*\s+/\s*$": {
        "risk": 1.0,
        "description": "递归强制删除根目录",
        "action": "block",
    },
    r"rm\s+-[a-zA-Z]*f[a-zA-Z]*r[a-zA-Z]*\s+/\s*$": {
        "risk": 1.0,
        "description": "递归强制删除根目录",
        "action": "block",
    },
    r"rm\s+--recursive\s+--force\s+/": {
        "risk": 1.0,
        "description": "递归强制删除根目录",
        "action": "block",
    },
    r"rm\s+-rf\s+/\*": {
        "risk": 1.0,
        "description": "递归强制删除根目录所有文件",
        "action": "block",
    },
    r"mkfs\.?": {
        "risk": 0.95,
        "description": "格式化文件系统",
        "action": "block",
    },
    r":\(\)\s*\{.*\|.*\&\}\s*;": {
        "risk": 1.0,
        "description": "Fork 炸弹 - 耗尽系统进程资源",
        "action": "block",
    },
    r"chmod\s+777\s+/": {
        "risk": 0.9,
        "description": "对根目录设置最大权限",
        "action": "block",
    },
    r"chown\s+-R\s+root:root\s+/": {
        "risk": 0.9,
        "description": "递归修改根目录所有者为 root",
        "action": "block",
    },
    r"dd\s+if=.+\s+of=/dev/sd": {
        "risk": 0.95,
        "description": "直接写入磁盘设备",
        "action": "block",
    },
    r">\s*/dev/sd[a-z]": {
        "risk": 0.9,
        "description": "覆写磁盘设备",
        "action": "block",
    },
    r"mv\s+/\s+/dev/null": {
        "risk": 1.0,
        "description": "将根目录移动到空设备",
        "action": "block",
    },
    r"shutdown\s+(-h|--halt)\s+now": {
        "risk": 0.8,
        "description": "立即关机",
        "action": "confirm",
    },
    r"shutdown\s+-r\s+now": {
        "risk": 0.8,
        "description": "立即重启",
        "action": "confirm",
    },
    r"\breboot\b": {
        "risk": 0.8,
        "description": "重启系统",
        "action": "confirm",
    },
    r"\bhalt\b": {
        "risk": 0.8,
        "description": "停止系统",
        "action": "confirm",
    },
    r"init\s+0": {
        "risk": 0.85,
        "description": "切换到运行级别 0 (关机)",
        "action": "confirm",
    },
    r"systemctl\s+poweroff": {
        "risk": 0.85,
        "description": "通过 systemd 关机",
        "action": "confirm",
    },
    r"wget\s+.*\|\s*(ba)?sh": {
        "risk": 0.9,
        "description": "下载并直接执行脚本",
        "action": "block",
    },
    r"curl\s+.*\|\s*(ba)?sh": {
        "risk": 0.9,
        "description": "下载并直接执行脚本",
        "action": "block",
    },
    r"\beval\s*\(": {
        "risk": 0.7,
        "description": "动态执行代码",
        "action": "warn",
    },
    r"\bexec\s*\(": {
        "risk": 0.7,
        "description": "执行外部程序",
        "action": "warn",
    },
    r"nc\s+-[a-zA-Z]*l": {
        "risk": 0.8,
        "description": "Netcat 监听模式 - 潜在后门",
        "action": "block",
    },
    r"iptables\s+-F": {
        "risk": 0.85,
        "description": "清空防火墙规则",
        "action": "confirm",
    },
    r"\buserdel\b": {
        "risk": 0.75,
        "description": "删除用户账户",
        "action": "confirm",
    },
    r"\bgroupdel\b": {
        "risk": 0.75,
        "description": "删除用户组",
        "action": "confirm",
    },
    r"passwd\s+root": {
        "risk": 0.9,
        "description": "修改 root 密码",
        "action": "block",
    },
    r"echo\s+.*>\s*/etc/passwd": {
        "risk": 1.0,
        "description": "覆写用户密码文件",
        "action": "block",
    },
    r"echo\s+.*>\s*/etc/shadow": {
        "risk": 1.0,
        "description": "覆写影子密码文件",
        "action": "block",
    },
    r"echo\s+.*>\s*/etc/sudoers": {
        "risk": 1.0,
        "description": "覆写 sudoers 配置",
        "action": "block",
    },
    r">\s*/etc/(passwd|shadow|sudoers)": {
        "risk": 1.0,
        "description": "覆写系统关键配置文件",
        "action": "block",
    },
}

DANGEROUS_PARAMS: Dict[str, float] = {
    "--no-preserve-root": 0.3,
    "--force": 0.2,
    "-f": 0.15,
    "--recursive": 0.2,
    "-r": 0.15,
    "--yes": 0.15,
    "-y": 0.15,
    "--delete": 0.25,
    "--hard": 0.2,
    "--remove": 0.2,
    "--purge": 0.25,
    "--all": 0.1,
    "-a": 0.1,
    "--interactive=never": 0.2,
}

PROTECTED_PATHS: List[str] = [
    r"^/$",
    r"^/etc\b",
    r"^/etc/passwd",
    r"^/etc/shadow",
    r"^/etc/sudoers",
    r"^/boot\b",
    r"^/dev\b",
    r"^/proc\b",
    r"^/sys\b",
    r"^/var/lib\b",
    r"^/root\b",
    r"^/usr/lib/systemd\b",
    r"^/usr/bin\b",
    r"^/usr/sbin\b",
    r"^/lib/modules\b",
    r"^/lib/systemd\b",
    r"^/run\b",
    r"^/sbin\b",
    r"^/bin\b",
    r"^/usr/lib\b",
]

INJECTION_PATTERNS_EN: List[str] = [
    r"[Ii]gnore\s+(all\s+)?(previous|prior|above)\s+(instructions|rules|commands|prompts)",
    r"[Dd]isregard\s+(all\s+)?(prior|previous|earlier)\s+(instructions|commands|rules)",
    r"[Ff]orget\s+(all\s+)?(previous|prior|the)\s+(rules|instructions|constraints)",
    r"[Yy]ou\s+are\s+now\s+(a|an)\s+",
    r"[Ss]ystem\s+prompt\s+(override|replace|ignore|bypass)",
    r"[Jj]ailbreak",
    r"DAN\s+mode",
    r"[Aa]ct\s+as\s+(if\s+)?(you\s+are\s+)?(an?\s+)?(unrestricted|unfiltered|unlimited)",
    r"[Bb]ypass\s+(all\s+)?(safety|security|content)\s+(filter|check|restriction|guardrail)",
    r"[Rr]ole\s*play\s+as\s+(a\s+)?(hacker|attacker|malicious)",
    r"[Pp]retend\s+(you|that)\s+(are|have)\s+no\s+(restrictions|limitations|rules|filters)",
    r"[Dd]o\s+anything\s+now",
    r"[Ee]nable\s+(developer|debug|god|admin)\s+mode",
    r"[Rr]emove\s+(all\s+)?(safety|content)\s+(filters?|restrictions?|guardrails?)",
    r"[Rr]espond\s+(to\s+)?(everything|all\s+requests)\s+without\s+(restriction|filter|limitation)",
    r"[Tt]he\s+above\s+(instructions?|prompt)\s+(are|is)\s+(wrong|incorrect|outdated|void)",
    r"[Nn]ew\s+(system\s+)?(instructions?|rules|prompt)\s*:",
    r"\[SYSTEM\]|\[INST\]|<\|system\|>|<\|im_start\|>system",
    r"[Oo]riginal\s+(instructions?|rules|prompt)\s+(are|is)\s+(now\s+)?(invalid|void|replaced)",
]

INJECTION_PATTERNS_CN: List[str] = [
    r"忽略(之前|上面|以上|所有)(的)?(指令|规则|提示|命令|要求|约束)",
    r"忽略(你|系统)(的)?(之前|上面|所有)(指令|规则|提示|命令|要求)",
    r"忽略(你|系统)?(的)?(之前|上面|所有)?(的)?(安全|防护)(设定|配置|规则|策略)",
    r"忘记(之前|所有|上面)(的)?(规则|指令|约束|限制)",
    r"你现在是",
    r"系统提示(覆盖|替换|忽略|绕过)",
    r"绕过(所有|全部)?(安全|内容|防护)(过滤|检查|限制|规则)",
    r"扮演(一个)?(没有|不受|无)(任何)?(限制|约束|规则)(的|地)",
    r"假装(你)?(没有|不受|无)(任何)?(限制|约束|规则|过滤)",
    r"开发者模式|上帝模式|管理员模式",
    r"以上(指令|规则|提示|命令)(无效|作废|错误|过时)",
    r"新的(系统)?(指令|规则|提示)\s*[:：]",
    r"解除(所有|全部)?(限制|约束|过滤|防护)",
    r"不要(遵守|遵循|理会|管)(任何|之前|上面)(的)?(规则|指令|限制)",
    r"从现在开始(你)?(没有|不受|无)(任何)?(限制|约束|规则)",
]

ALLOWED_COMMANDS: List[str] = [
    "ls",
    "ps",
    "df",
    "du",
    "free",
    "uptime",
    "whoami",
    "hostname",
    "uname",
    "date",
    "echo",
    "cat",
    "ss",
    "netstat",
    "ip",
    "iostat",
    "vmstat",
    "top",
    "id",
    "w",
]

INTENT_KEYWORDS: Dict[str, Dict[str, float]] = {
    "query": {
        "查看": 1.0,
        "显示": 1.0,
        "列出": 1.0,
        "获取": 1.0,
        "状态": 0.8,
        "list": 1.0,
        "show": 1.0,
        "get": 1.0,
        "check": 0.9,
        "查询": 1.0,
        "监控": 0.9,
        "搜索": 0.8,
        "find": 0.8,
        "search": 0.8,
        "info": 0.9,
        "信息": 0.9,
        "详情": 0.9,
    },
    "diagnose": {
        "排查": 1.0,
        "分析": 1.0,
        "诊断": 1.0,
        "为什么": 1.0,
        "原因": 0.9,
        "troubleshoot": 1.0,
        "diagnose": 1.0,
        "analyze": 1.0,
        "why": 1.0,
        "日志": 0.7,
        "异常": 0.8,
        "错误": 0.7,
        "故障": 0.9,
        "问题": 0.6,
        "log": 0.7,
        "error": 0.7,
        "debug": 0.8,
    },
    "modify": {
        "修改": 1.0,
        "设置": 1.0,
        "配置": 1.0,
        "重启": 1.0,
        "启动": 1.0,
        "停止": 1.0,
        "set": 1.0,
        "config": 1.0,
        "restart": 1.0,
        "start": 1.0,
        "stop": 1.0,
        "开启": 1.0,
        "关闭": 1.0,
        "enable": 0.9,
        "disable": 0.9,
        "更新": 0.9,
        "update": 0.9,
        "安装": 0.8,
        "install": 0.8,
    },
    "dangerous": {
        "删除": 1.0,
        "清空": 1.0,
        "格式化": 1.0,
        "终止": 0.9,
        "杀掉": 1.0,
        "kill": 1.0,
        "rm": 1.0,
        "delete": 1.0,
        "format": 1.0,
        "destroy": 1.0,
        "卸载": 0.8,
        "uninstall": 0.8,
        "drop": 0.9,
        "truncate": 0.9,
        "wipe": 1.0,
        "erase": 1.0,
        "purge": 0.9,
    },
}

PATH_WHITELIST: List[str] = [
    r"^/tmp\b",
    r"^/var/log\b",
    r"^/home\b",
    r"^/opt\b",
]

PATH_BLACKLIST: List[str] = [
    r"^/etc/passwd",
    r"^/etc/shadow",
    r"^/etc/sudoers",
    r"^/boot\b",
    r"^/usr/lib/systemd\b",
    r"^/var/log\b",
]

BLOCKED_PIDS: set = {0, 1, 2}

UNICODE_HOMOGLYPHS: Dict[str, str] = {
    "\u0430": "a",
    "\u0435": "e",
    "\u043e": "o",
    "\u0440": "p",
    "\u0441": "c",
    "\u0443": "y",
    "\u0445": "x",
    "\u0410": "A",
    "\u0412": "B",
    "\u0415": "E",
    "\u041a": "K",
    "\u041c": "M",
    "\u041d": "H",
    "\u041e": "O",
    "\u0420": "P",
    "\u0421": "C",
    "\u0422": "T",
    "\u0423": "Y",
    "\u0425": "X",
}

ZERO_WIDTH_CHARS: List[str] = [
    "\u200b",
    "\u200c",
    "\u200d",
    "\u200e",
    "\u200f",
    "\u2060",
    "\u2061",
    "\u2062",
    "\u2063",
    "\u2064",
    "\ufeff",
    "\u00ad",
    "\u034f",
    "\u180e",
]

CONTROL_CHAR_RANGES: List[tuple] = [
    (0x00, 0x08),
    (0x0B, 0x0C),
    (0x0E, 0x1F),
    (0x7F, 0x7F),
    (0x80, 0x9F),
]

RISK_SCORE_THRESHOLDS: Dict[str, float] = {
    "safe": 0.0,
    "low": 0.3,
    "medium": 0.5,
    "high": 0.7,
    "critical": 0.9,
}
